version: '2'
volumes:
    resin-data:
services:
  ledmatrix:
    build: ./ledmatrix
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/mem:/dev/mem"
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
    depends_on:
      - ws
  proxy:
    build: ./proxy
    restart: always
    privileged: true
    network_mode: host
  network:
    build: ./network
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  airplay:
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - ws
  spotify:
    build: ./spotify
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - ws
  mopidy:
    build: ./mopidy
    volumes:
      - 'resin-data:/data'
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - ws
  file-manager:
    build: ./file-manager
    volumes:
      - 'resin-data:/data'
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - ws
  supervisor:
    build: ./supervisor
    restart: always
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    privileged: true
    depends_on:
      - ws
  ws:
    build: ./ws
    restart: always
    privileged: true
    network_mode: host
    expose:
      - "1337"
